on: push
name: Deploy website on VPS
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        -  name: Get latest code
           uses: actions/checkout@v6

        -  name: Sync files
           uses: SamKirkland/FTP-Deploy-Action@v4.4.0
           with:
             server: 20.215.35.36
             username: student
             password: Student1234#*
             protocol: ftp
             server-dir: /var/www/html/rafalhachula
