name: Build and Deploy with Ansible
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
   install-on-vps:
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4
           
         - name: Install Ansible
           run: |
            sudo apt update
            sudo apt install -y ansible

         - name: Configure SSH key
           run: |
            # mkdir -p ~/.ssh
            # echo "${{secrets.VPS_SSH_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{secrets.VPS_HOST}} >> ~/.ssh/known-hosts

         - name: Create Ansible inventory
           run: |
            cat > amsisble/inventory.ini <<EOF
            [vps]
            server ansible_host=${{secrets.VPS_HOST}} ansible user=${{secrets.VPS_USER}}

         - name: Run Ansible playbook
           run: |
            ansible-playbook -i ansible/inventory.ini ansible /install.yml
            [vps]
            server ansible_host=${{secrets.VPS_HOST}} ansible user=${{secrets.VPS_USER}}
     
         with:
             server: ${{ secrets.ftp_hostname }}
             username: ${{ secrets.ftp_username }}
             password: ${{ secrets.ftp_password }}
             protocol: ${{ secrets.ftp_protocol }}
             server-dir: ${{ secrets.ftp_srvdir }}
               
      
